# 
# Copyright (c) 2020 IAR Systems AB
#
# BXARM CI Workflow Example
#
# See LICENSE for detailed license information
#

name: IAR Build Tools CI

# Controls when the action will run. Triggers the workflow on push 
on:
  push:
    branches: [ dev* ]

env:
  BUILD_TYPE: Debug  
  IARBUILD_PATH: /opt/iarsystems/bxarm/common/bin
  IARBUILD_OPTS: -log all -parallel 2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  # This workflow contains a single job called "iarbuild"
  iarbuild:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Library
        run: $IARBUILD_PATH/iarbuild ./workspace/library/library.ewp       -build $BUILD_TYPE $IARBUILD_OPTS

      - name: Build Component 1
        run: $IARBUILD_PATH/iarbuild ./workspace/component1/component1.ewp -build $BUILD_TYPE $IARBUILD_OPTS
      
      - name: Build Component 2
        run: $IARBUILD_PATH/iarbuild ./workspace/component2/component2.ewp -build $BUILD_TYPE $IARBUILD_OPTS
